# Generated by Django 2.2.5 on 2022-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220710_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
