# Generated by Django 2.2.5 on 2022-08-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetions',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'COMFIRMES'), ('canceled', 'CANCELED')], default='pending', max_length=12),
        ),
    ]
